framework:
    cache:
        app: cache.adapter.filesystem
        pools:
            # @todo
            cache.channel.request:
                default_lifetime: 300 # 5 minutes
                tags:             true
                adapters:
                    - cache.adapter.array
                    - cache.adapter.filesystem
