framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            sync:  'sync://'
            commands:
                #dsn: 'doctrine://default?queue_name=commands'
                dsn: 'sync://'
                retry_strategy:
                    max_retries: 0
            events:
                #dsn: 'doctrine://default?queue_name=events'
                dsn: 'sync://'
                retry_strategy:
                    max_retries: 0

        routing:
            'CommerceKitty\Message\Command\CommandInterface': commands
            'CommerceKitty\Message\Event\EventInterface': events
            'CommerceKitty\Message\Query\QueryInterface': sync

        default_bus: command.bus
        buses:
            # Type-hint with Symfony\Component\Messenger\MessageBusInterface $commandBus
            command.bus:
                middleware:
                    - validation
            # Type-hint with Symfony\Component\Messenger\MessageBusInterface $queryBus
            query.bus:
                middleware:
                    - validation
            # Type-hint with Symfony\Component\Messenger\MessageBusInterface $eventBus
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
