event_store_index:
    path:       /_event-stores.{_format}
    controller: CommerceKitty\Controller\EventStoreController::index
    defaults:
        _format: html
    requirements:
        _format: html|json
event_store_aggregate_index:
    path:       /_event-stores/{aggregate}.{_format}
    controller: CommerceKitty\Controller\EventStoreController::aggregateIndex
    defaults:
        _format: html
    requirements:
        _format: html|json
event_store_aggregate_delete:
    path:       /_event-stores/{aggregate}/{id}/delete.{_format}
    controller: CommerceKitty\Controller\EventStoreController::aggregateDelete
    defaults:
        _format: html
    requirements:
        _format: html|json
event_store_aggregate_show:
    path:       /_event-stores/{aggregate}/{id}.{_format}
    controller: CommerceKitty\Controller\EventStoreController::aggregateShow
    defaults:
        _format: html
    requirements:
        _format: html|json
