# <-- Generic
homepage:
    methods:    GET
    path:       /
    controller: App\Controller\DefaultController::index
# --> Generic

# --> Security
login:
    path:       /login
    controller: App\Controller\SecurityController::login
logout:
    path:       /logout
    controller: App\Controller\SecurityController::logout
# <-- Security

# <-- ChangePassword
change_password:
    methods:    GET|POST
    path:       /change-password.{_format}
    controller: App\Controller\ChangePasswordController::changePassword
    defaults:
        _format: html
    requirements:
        _format: html|json
# --> ChangePassword

# <-- Profile
profile_edit:
    methods:    GET|POST
    path:       /profile/edit.{_format}
    controller: App\Controller\ProfileController::edit
    defaults:
        _format: html
    requirements:
        _format: html|json
# --> Profile

# --> Channel
channel_index:
    methods:    GET
    path:       /channels.{_format}
    controller: App\Controller\EntityController::index
    defaults:
        _format:            html
        _entity_class_name: Channel
    requirements:
        _format: html|json
channel_purge:
    methods:    GET|DELETE
    path:       /channels/purge.{_format}
    controller: App\Controller\EntityController::purge
    defaults:
        _format:            html
        _entity_class_name: Channel
    requirements:
        _format: html|json
channel_select_type:
    methods:    GET|POST
    path:       /channels/select-type.{_format}
    controller: App\Controller\ChannelController::selectType
    defaults:
        _format: html
    requirements:
        _format: html|json
channel_new:
    methods:    GET|POST
    path:       /channels/new.{_format}
    controller: App\Controller\ChannelController::new
    defaults:
        _format: html
    requirements:
        _format: html|json
channel_edit:
    methods:    GET|POST
    path:       /channels/{id}/edit.{_format}
    controller: App\Controller\ChannelController::edit
    defaults:
        _format: html
    requirements:
        _format: html|json
channel_clone:
    methods:    GET|POST
    path:       /channels/{id}/clone.{_format}
    controller: App\Controller\EntityController::clone
    defaults:
        _format:            html
        _entity_class_name: Channel
    requirements:
        _format: html|json
channel_delete:
    methods:    GET|DELETE
    path:       /channels/{id}/delete.{_format}
    controller: App\Controller\EntityController::delete
    defaults:
        _format:            html
        _entity_class_name: Channel
    requirements:
        _format: html|json
channel_test_connection:
    methods:    GET|POST
    path:       /channels/{id}/test-connection.{_format}
    controller: App\Controller\ChannelController::testConnection
    defaults:
        _format: html
    requirements:
        _format: html|json
channel_import_products:
    methods:    GET|POST
    path:       /channels/{id}/import-products.{_format}
    controller: App\Controller\ChannelController::importProducts
    defaults:
        _format: html
    requirements:
        _format: html|json
channel_import_orders:
    methods:    GET|POST
    path:       /channels/{id}/import-orders.{_format}
    controller: App\Controller\ChannelController::importOrders
    defaults:
        _format: html
    requirements:
        _format: html|json
channel_export_inventory:
    methods:    GET|POST
    path:       /channels/{id}/export-inventory.{_format}
    controller: App\Controller\ChannelController::exportInventory
    defaults:
        _format: html
    requirements:
        _format: html|json
channel_export_listings:
    methods:    GET|POST
    path:       /channels/{id}/export-listings.{_format}
    controller: App\Controller\ChannelController::exportListings
    defaults:
        _format: html
    requirements:
        _format: html|json
channel_show:
    methods:    GET
    path:       /channels/{id}.{_format}
    controller: App\Controller\EntityController::show
    defaults:
        _format:            html
        _entity_class_name: Channel
    requirements:
        _format: html|json
# <-- Channel

# --> Customer
customer_index:
    methods:    GET
    path:       /customers.{_format}
    controller: App\Controller\EntityController::index
    defaults:
        _format:            html
        _entity_class_name: Customer
    requirements:
        _format: html|json
customer_purge:
    methods:    GET|DELETE
    path:       /customers/purge.{_format}
    controller: App\Controller\EntityController::purge
    defaults:
        _format:            html
        _entity_class_name: Customer
    requirements:
        _format: html|json
customer_new:
    methods:    GET|POST
    path:       /customers/new.{_format}
    controller: App\Controller\EntityController::new
    defaults:
        _format:            html
        _entity_class_name: Customer
    requirements:
        _format: html|json
customer_edit:
    methods:    GET|POST
    path:       /customers/{id}/edit.{_format}
    controller: App\Controller\EntityController::edit
    defaults:
        _format:            html
        _entity_class_name: Customer
    requirements:
        _format: html|json
customer_delete:
    methods:    GET|DELETE
    path:       /customers/{id}/delete.{_format}
    controller: App\Controller\EntityController::delete
    defaults:
        _format:            html
        _entity_class_name: Customer
    requirements:
        _format: html|json
customer_clone:
    methods:    GET|POST
    path:       /customers/{id}/clone.{_format}
    controller: App\Controller\EntityController::clone
    defaults:
        _format:            html
        _entity_class_name: Customer
    requirements:
        _format: html|json
customer_show:
    methods:    GET
    path:       /customers/{id}.{_format}
    controller: App\Controller\EntityController::show
    defaults:
        _format:            html
        _entity_class_name: Customer
    requirements:
        _format: html|json
# <-- Customer

# <-- Inventory
inventory_set:
    methods:    GET|POST
    path:       /inventory/{id}/set.{_format}
    controller: App\Controller\InventoryController::set
    defaults:
        _format: html
    requirements:
        _format: html|json
inventory_increment:
    methods:    GET|POST
    path:       /inventory/{id}/increment.{_format}
    controller: App\Controller\InventoryController::increment
    defaults:
        _format: html
    requirements:
        _format: html|json
inventory_decrement:
    methods:    GET|POST
    path:       /inventory/{id}/decrement.{_format}
    controller: App\Controller\InventoryController::decrement
    defaults:
        _format: html
    requirements:
        _format: html|json
inventory_delete:
    methods:    GET|DELETE
    path:       /inventory/{id}/delete.{_format}
    controller: App\Controller\EntityController::delete
    defaults:
        _format:            html
        _entity_class_name: Inventory
    requirements:
        _format: html|json
# --> Inventory

# --> Product
product_index:
    methods:    GET
    path:       /products.{_format}
    controller: App\Controller\EntityController::index
    defaults:
        _format:            html
        _entity_class_name: Product
    requirements:
        _format: html|json
product_select_type:
    methods:    GET|POST
    path:       /products/select-type.{_format}
    controller: App\Controller\ProductController::selectType
    defaults:
        _format: html
    requirements:
        _format: html|json
product_new:
    methods:    GET|POST
    path:       /products/new.{_format}
    controller: App\Controller\ProductController::new
    defaults:
        _format: html
    requirements:
        _format: html|json
product_purge:
    methods:    GET|DELETE
    path:       /products/purge.{_format}
    controller: App\Controller\EntityController::purge
    defaults:
        _format:            html
        _entity_class_name: Product
    requirements:
        _format: html|json
product_edit:
    methods:    GET|POST
    path:       /products/{id}/edit.{_format}
    controller: App\Controller\EntityController::edit
    defaults:
        _format:            html
        _entity_class_name: Product
    requirements:
        _format: html|json
product_delete:
    methods:    GET|DELETE
    path:       /products/{id}/delete.{_format}
    controller: App\Controller\EntityController::delete
    defaults:
        _format:            html
        _entity_class_name: Product
    requirements:
        _format: html|json
product_clone:
    methods:    GET|POST
    path:       /products/{id}/clone.{_format}
    controller: App\Controller\EntityController::clone
    defaults:
        _format:            html
        _entity_class_name: Product
    requirements:
        _format: html|json
product_inventory:
    methods:    GET
    path:       /products/{id}/inventory.{_format}
    controller: App\Controller\ProductController::inventory
    defaults:
        _format: html
    requirements:
        _format: html|json
product_show:
    methods:    GET
    path:       /products/{id}.{_format}
    controller: App\Controller\EntityController::show
    defaults:
        _format:            html
        _entity_class_name: Product
    requirements:
        _format: html|json
# <-- Product

# <-- ProductInventory
product_inventory_select_warehouse:
    methods:    GET|POST
    path:       /products/{id}/inventory/select-warehouse.{_format}
    controller: App\Controller\ProductInventoryController::selectWarehouse
    defaults:
        _format: html
    requirements:
        _format: html|json
product_inventory_new:
    methods:    GET|POST
    path:       /products/{id}/inventory/new.{_format}
    controller: App\Controller\ProductInventoryController::new
    defaults:
        _format: html
    requirements:
        _format: html|json
# --> ProductInventory

# --> Vendor
vendor_index:
    methods:    GET
    path:       /vendors.{_format}
    controller: App\Controller\EntityController::index
    defaults:
        _format:            html
        _entity_class_name: Vendor
    requirements:
        _format: html|json
vendor_purge:
    methods:    GET|DELETE
    path:       /vendors/purge.{_format}
    controller: App\Controller\EntityController::purge
    defaults:
        _format:            html
        _entity_class_name: Vendor
    requirements:
        _format: html|json
vendor_new:
    methods:    GET|POST
    path:       /vendors/new.{_format}
    controller: App\Controller\EntityController::new
    defaults:
        _format:            html
        _entity_class_name: Vendor
    requirements:
        _format: html|json
vendor_edit:
    methods:    GET|POST
    path:       /vendors/{id}/edit.{_format}
    controller: App\Controller\EntityController::edit
    defaults:
        _format:            html
        _entity_class_name: Vendor
    requirements:
        _format: html|json
vendor_clone:
    methods:    GET|POST
    path:       /vendors/{id}/clone.{_format}
    controller: App\Controller\EntityController::clone
    defaults:
        _format:            html
        _entity_class_name: Vendor
    requirements:
        _format: html|json
vendor_delete:
    methods:    GET|DELETE
    path:       /vendors/{id}/delete.{_format}
    controller: App\Controller\EntityController::delete
    defaults:
        _format:            html
        _entity_class_name: Vendor
    requirements:
        _format: html|json
vendor_show:
    methods:    GET
    path:       /vendors/{id}.{_format}
    controller: App\Controller\EntityController::show
    defaults:
        _format:            html
        _entity_class_name: Vendor
    requirements:
        _format: html|json
# <-- Vendor

# <-- Warehouse
warehouse_index:
    methods:    GET
    path:       /warehouses.{_format}
    controller: App\Controller\EntityController::index
    defaults:
        _format:            html
        _entity_class_name: Warehouse
    requirements:
        _format: html|json
warehouse_purge:
    methods:    GET|DELETE
    path:       /warehouses/purge.{_format}
    controller: App\Controller\EntityController::purge
    defaults:
        _format:            html
        _entity_class_name: Warehouse
    requirements:
        _format: html|json
warehouse_new:
    methods:    GET|POST
    path:       /warehouses/new.{_format}
    controller: App\Controller\EntityController::new
    defaults:
        _format:            html
        _entity_class_name: Warehouse
    requirements:
        _format: html|json
warehouse_edit:
    methods:    GET|POST
    path:       /warehouses/{id}/edit.{_format}
    controller: App\Controller\EntityController::edit
    defaults:
        _format:            html
        _entity_class_name: Warehouse
    requirements:
        _format: html|json
warehouse_clone:
    methods:    GET|POST
    path:       /warehouses/{id}/clone.{_format}
    controller: App\Controller\EntityController::clone
    defaults:
        _format:            html
        _entity_class_name: Warehouse
    requirements:
        _format: html|json
warehouse_delete:
    methods:    GET|DELETE
    path:       /warehouses/{id}/delete.{_format}
    controller: App\Controller\EntityController::delete
    defaults:
        _format:            html
        _entity_class_name: Warehouse
    requirements:
        _format: html|json
warehouse_show:
    methods:    GET
    path:       /warehouses/{id}.{_format}
    controller: App\Controller\EntityController::show
    defaults:
        _format:            html
        _entity_class_name: Warehouse
    requirements:
        _format: html|json
# --> Warehouse
